### ISSUE TITLE
Game Boy Resource suggestions

### ISSUE THREAD

**Issue by bbbbbr** [DogedomStudioS/retro-platform-jam-tools#1]
Some **Game Boy** related resources if you want to add them

Assembler:
* [RGBDS](https://github.com/gbdev/rgbds)[](https://github.com/gbdev/rgbds)[](https://github.com/gbdev/rgbds) - Assembler and linker package.

Engines and SDKs
* [GBDK-2020](https://github.com/gbdk-2020/gbdk-2020/)[](https://github.com/gbdk-2020/gbdk-2020/)[](https://github.com/gbdk-2020/gbdk-2020/) - SDK for the Game Boy that uses the SDCC toolchain.
* [ZGB](https://github.com/Zal0/ZGB)[](https://github.com/Zal0/ZGB)[](https://github.com/Zal0/ZGB) - A little engine for creating games for the Game Boy built on GBDK-2020.

Forums, Tutorials, Wikis, and Documentation
* [The Awesome Game Boy / Game Boy Color Development List](https://gbdev.io/resources.html) - Links to many resources for GB development.

**Comment by DSSDevelopment** [comment]
All of these have been added to the wiki. Thank you very much for the contribution!

**Comment by bbbbbr** [comment]
Thanks!
